### ISSUE TITLE
Multiple w/ server side data removes selected options

### ISSUE THREAD

**Issue by bakerac4** [miguelcobain/ember-cli-selectize#119]
Im wrapping ember-cli-selectize in my own type ahead component. It loads the data correctly, I select an item and it shows up in the select box. But then I start typing to find a different item and it removes the item I just selected from the select box. Is it possible to use server side data and multiple=true? 

```javascript
{{type-ahead modelName='friend' selection=selections multiple=true placeholder="Tag a friend"}}
```

The component hbs 
```javascript
{{ember-selectize
      content=data
      optionValuePath=optionValuePath
      optionLabelPath=optionLabelPath
      selection=selection
      placeholder=placeholder
      multiple=multiple
      update-filter="filterUpdate"
      add-item="itemSelected"}}
```

The component js

```javascript
import Ember from 'ember';
import DS from 'ember-data';

export default Ember.Component.extend({
    data: function() {
        var modelName = this.get('modelName'),
            filter = this.get('filter'),
            store = this.store;
            if (filter) {
                return DS.PromiseArray.create({
                    //do whatever you need to remotely fetch the models, based on the filter
                    promise: store.query(modelName, { name: filter })
                });
            } else {
                    return [];
            }
    }.property('modelName', 'filter'),
    selection: null,
    modelName: null,
    filter: null,
    optionValuePath: 'content.id',
    optionLabelPath: 'content.name',
    multiple: false,
    placeholder: 'Select an item',
    actions: {
        filterUpdate: function(filter) {
            this.set('filter', filter);
        }
    }
});
```

**Comment by miguelcobain** [comment]
@bakerac4 The problem here is that when you start typing, the options array is different.
It happens that the new data **doesn't** contain the item you selected previously.
The selected option must always be present the the options array.

You can fix this easily by always including the selected item in your `data` computed property.

Please consider using ember-power-select. It is an ember implementation of a select component in which I am also somehow involved.
Eventually ember-cli-selectize will be unmaintained in favor of ember-power-select.
