### ISSUE TITLE
Clearing multiple selection selectize generates model error

### ISSUE THREAD

**Issue by IAmJulianAcosta** [miguelcobain/ember-cli-selectize#123]
@miguelcobain what should I do when I have to clear a multiple selection?

I used what you said in #85 `this.set('selection', null)` and `this.set('selection', [])` but both generate this error:
```
Uncaught Error: Assertion Failed: The `attr` method is not available on DS.Model, a DS.Snapshot was probably expected. Are you passing a DS.Model instead of a DS.Snapshot to your serializer?

assert @ ember.debug.js:5223
assert @ ember.debug.js:12624
Ember.Object.extend.attr @ model.js:694
$.extend.removeItem @ selectize.js:2543
selectionObjectWasRemoved @ ember-selectize.js:529
selectionArrayWillChange @ ember-selectize.js:500
_selectionWillChange @ ember-selectize.js:420
(anonymous function) @ ember-selectize.js:432
```

**Comment by mszoernyi** [comment]
I'm getting the same error without resetting the selection myself.

- `ember-data 2.2.0`
- `ember 2.2.0`
- `ember-cli-selectize 4.2.0`

Using ember-selectize with `{{ember-selectize content=organizations optionLabelPath='name' selection=user.organizations multiple=true loading=organizations.isPending}}`

and `organizations` is set on the route with `this.store.findAll(‘organization’)`

I guess when loading the array is empty and because it fails here:  
https://github.com/brianreavis/selectize.js/blob/043420284064ad998b07e1abd9720f56c86d6614/dist/js/selectize.js#L1934

Seems like it's not passing the right object. Setting `optionValuePath` doesn't seems to fit, because I want the object as a value.

**Comment by IAmJulianAcosta** [comment]
Closing, is selectize issue, not ember-selectize

**Comment by IAmJulianAcosta** [comment]
@mszoernyi You should check the related issue, is a one-line fix.

**Comment by gogromat** [comment]
For those who still use **ember-cli-selectize**, if you install it (with ```ember install ember-cli-selectize```), you are still going to get this error, since the selectize.js branch used (if you check ```bower.json```) is: ```"selectize": "miguelcobain/selectize.js#master"```, which is an old version of forked selectize library. You want to replace it with something like ```"selectize": "0.12.4"``` which contains the fix to this problem.
