### ISSUE TITLE
Ember paper styling

### ISSUE THREAD

**Issue by avdmatamoros** [miguelcobain/ember-cli-selectize#129]
Is there a way I could get this to behave link ember paper's select?
(or get ember paper's select to work like selectize)

**Comment by miguelcobain** [comment]
What do you need from ember-cli-selectize that isn't in ember-paper's select?

**Comment by avdmatamoros** [comment]
I'm in need of search capabilities (autocomplete), multiple selection, etc.
If that is available in ember paper select, I don't quite see it in the docs.

**Comment by miguelcobain** [comment]
Closing this since this isn't an ember-cli-selectize issue.

If the question is styling, that is related with selectize itself (but that project is unmaintained).
If the question if ember-paper's functionality, that is related with ember-paper.

What ember-paper needs is a "Chips" implementation: https://material.angularjs.org/latest/demo/chips
That is the natural thing to do.

**Comment by avdmatamoros** [comment]
ok, so I'll open a ticket on ember paper's end
thanks
