### ISSUE TITLE
Exception thrown if `remove` action not specified 

### ISSUE THREAD

**Issue by domchristie** [miguelcobain/ember-cli-selectize#40]
Uncaught Error: Assertion Failed: The remove action was triggered on the component <app@component:ember-selectize::ember872>, but the action name (function () {
            // What we should really do here is wait until the end of the run loop
            // to determine if the element has been re-appended to a different
            // element.
            // In the interim, we will just re-render if that happens. It is more
            // important than elements get garbage collected.
            if (!this.removedFromDOM) { this.destroyElement(); }
          }) was not a string.

Fixed by adding a `remove` action:

    {{ember-selectize remove='someAction'}}

**Comment by miguelcobain** [comment]
Ok, we have to check if the action is specified before sending it.

**Comment by domchristie** [comment]
{{ember-selectize
      content=content
      selection=selection
      optionValuePath='email'
      optionLabelPath='fullName'
      multiple=true
      openOnFocus=false
      closeAfterSelect=true
      itemFunction=itemFunction
      optionFunction=optionFunction
      create='onCreate'
      createFilter=createFilter}}

ember-cli-selectize 0.2.0

**Comment by miguelcobain** [comment]
Damn, `remove` is a method of Ember.Component: http://emberjs.com/api/classes/Ember.Component.html#method_remove

Any suggestions?

/cc @sandstrom

**Comment by domchristie** [comment]
Would it be clearer if all the method/action names referred to `item` or `option`. e.g. `itemRemoved`?

**Comment by sandstrom** [comment]
I don't have a strong opinion on this, but I'd try to align with other ember components. `add-item` `select-item` etc. would be fairly close to http://emberjs.com/api/classes/Ember.Handlebars.helpers.html#toc_actions

Perhaps `type` could be `update-query` or similar. *Type* sounds almost like a low-level key-press, but I guess it's really sort of like a 'change' event on the input.

**Comment by miguelcobain** [comment]
`type` also sounds like the "type" of a class.
From the examples, I think it is clear that the names should be snake-cased. So anything camelCased is ruled out.
The item suffix makes this less likely to collide with existing and future properties/methods.
I think we should stick with `{action}-{subject of the action}`.

I prefer `filter` to `query` because we may not be dealing with a query. Also, selectize docs call this action "filtering options", hence filter:
> `onType(str)` Invoked when the user types while filtering options.

We end up with:

- `add-item`
- `remove-item`
- `select-item`
- `create-item`
- `update-filter`

I like this, and all of them have a decent explanation. Enough of overthinking for me. :smile:

**Comment by miguelcobain** [comment]
Updated to `0.3.0` since this is a breaking change.
Solved.

**Comment by sandstrom** [comment]
Awesome! :fireworks:
