### ISSUE TITLE
Provide a Way to Choose Selectize Stylesheet

### ISSUE THREAD

**Issue by heathharrelson** [miguelcobain/ember-cli-selectize#5]
The addon currently unconditionally includes the bower_components/selectize/dist/css/selectize.css stylesheet. My Ember app is using Bootstrap 3, though, so this doesn't look so great. I was able to get things to look nice by changing index.js to use selectize.bootstrap3.css, but it would be nicer to have a way to configure which stylesheet is included.

I'm not familiar with developing Ember CLI addons or Node applications in general, and I don't see anything of obvious use [in the Ember CLI documentation](http://www.ember-cli.com/#developing-addons-and-blueprints). If you have any idea how this could be implemented, I'd be happy to implement the feature myself and send you a PR.

**Comment by miguelcobain** [comment]
Fixed in https://github.com/miguelcobain/ember-cli-selectize/commit/0e04a24482beea8998bf57af62b27da077d26c71.

Please update ember-cli-selectize.
Added a [theme customization](https://github.com/miguelcobain/ember-cli-selectize#theme-customization) section to the README.

Let me know if this works for you.

**Comment by heathharrelson** [comment]
Works for me. Thanks.
