### ISSUE TITLE
Adding selectize 'plugins' to config

### ISSUE THREAD

**Issue by knownasilya** [miguelcobain/ember-cli-selectize#7]
Would be nice if the `plugins` array could be specified. It'll most likely have to be done in the user's `config/environment.js`.

**Comment by miguelcobain** [comment]
Yes. For now you can reopen the ember-selectize component and override the `plugins` array.

Question: to keep selectize configuration in a single place, could it be possible/desirable to set the environment from the Brocfile?

**Comment by knownasilya** [comment]
Not sure if it's possible, but it's possible to get the config in the addon's `index.js` from the user's `config/environment.js`. See [here](https://github.com/knownasilya/ember-cli-toggle/blob/master/index.js#L14).

**Comment by miguelcobain** [comment]
So, what do you think of centralizing all the configuration in `config/environment.js`?
Ember-cli configuration is confusing right now.

Quoting a tweet from @EmberSherpa:

>TIL: EmberCLI has 3 levels of config
>
>App: config/environment.js
>Asset Compilation: Brocfile.js
>CLI: Task parameters
>
>Thanks @abuiles

So, I guess this is a matter of whether this is an app or asset compilation configuration.

Possible selectize configurations (at least for now):
- Theme
- Plugins

Changing theme **does** change the assets that are included, but not the app or the code itself (just css files) -> Brocfile
Changing plugins **does not** affect the assets that are included because all the selectize plugins are included in the same js file -> environment

We reach a conclusion that doesn't make me happy. Perhaps we should just use environment.js, considering the theme an app config, but just one that doesn't have any impact on code.

**Comment by miguelcobain** [comment]
@knownasilya, I also don't know how this component would behave with plugins like "drag_drop" or "optgroup_columns", but nevertheless this configuration option should exist.

**Comment by mar3les** [comment]
#15 c66898d118466a6285d4355f7a544577b3635803

**Comment by miguelcobain** [comment]
Closed in PR #15
