### ISSUE TITLE
defining optionValuePath and optionLabelPath, with or without "content." prefix

### ISSUE THREAD

**Issue by grapho** [miguelcobain/ember-cli-selectize#82]
I just noticed that it does not seem to matter if "optionValuePath" or "optionLabelPath" are prefixed with "content."

the "label" value for the options seem to display correctly regardless,  and the "value" that gets sent up via the `select-item` action is still just the option object itself rather than just the selected value like i assumed it might.

I dont know if that is intended or not?  so currently when dealing with the emitted actions I make sure that the handler parses out the actual value that i want to set to a model attr.

ideally if the `optionValuePath` is set, it would be nice if i could just do a `select-item=(action (mut property))`  rather than explicitly create an action handler for each select box i need.

am I wrong thinking this?  maybe i am stuck in a two-way-binding mode of thinking?

**Comment by miguelcobain** [comment]
> I just noticed that it does not seem to matter if "optionValuePath" or "optionLabelPath" are prefixed with "content."

Yes, it works with or without the `content` prefix. The reason is to be interchangeable with Ember.Select API which requires `content.` (at least some time ago it did).

Let me see if I understand what you mean:
If `optionValuePath` was set, you expect the `select-item` action to receive a `value` and not the whole option object, right?

> ideally if the optionValuePath is set, it would be nice if i could just do a select-item=(action (mut property)) rather than explicitly create an action handler for each select box i need.

That was my concern when "data down, actions up" emerged. Please read #34 and the linked discuss post. Basically there are still valid use cases for two-way databinding.
It would not be practical at all to use "data down, actions up" within my app. I have dozens of select boxes. I can't write actions for all of them. I just let the component change the value for me.

Regarding your sugestion, I still think that `select-item` action should get the whole object. People may want to set an Ember data relationship with that, for example.
I'm not opposed to pass the value as a second argument or in another `select-value` action.

**Comment by grapho** [comment]
@miguelcobain  actually in terms of adta-down-actions-up... `select-value` that sounds exactly like something that i would love as an option!  as well as `add-value` remove-value` in the case of a "multiple select".

there are certainly times when passing the whole object through is good.. but as you have said, i dont want to have to make an action handler every time in just need a single value _of_ the passed object.

I might be able to help out a little, if you feel like you would want to do that

**Comment by miguelcobain** [comment]
I'm not opposed to it. It should be really simples. Just mimic the existing actions but with just the value as parameter.
Also the tests should be very similar.

I'll take a look at this when I have the time. But a PR would speed this process a lot, of course.

**Comment by grapho** [comment]
I will see what i can pull together

**Comment by grapho** [comment]
@miguelcobain  PR #83

I'm afraid I am usless when it comes to writing tests.  However this is how i imagine it could work.. what do you think?
