### ISSUE TITLE
.clear() doesn't completely reset the selection

### ISSUE THREAD

**Issue by dfalling** [miguelcobain/ember-cli-selectize#85]
I want to use a selectize list as an action menu.  When an item is selected, an action is performed, and the selectize component returns to a cleared state.  I'm doing this by clearing out selectize's selection in my `select-item` action handler.  This visually appears to clear out selectize, but if you select the same action again, `select-item` isn't fired, and the item them becomes selected.

Template:

```javascript
{{ember-selectize
    optionValuePath='content.id'
    optionLabelPath='content.label'
    content=items
    select-item='selectItem'}}

<br/>
Current item: {{item.label}}
```

Controller:
```javascript
import Ember from 'ember';

export default Ember.Component.extend({
  items: [{id: 0, label: 'first'}, {id: 1, label: 'second'}],
  
  actions: {
    selectItem: function(item) {
      this.set('item', item);
      this.$('.ember-selectize')[0].selectize.clear(true);
    }
  }
});
```

Am I simply doing this wrong, or is this a bug with selectize?

**Comment by miguelcobain** [comment]
That's because you're accessing the selective instance directly, bypassing ember-selectize completely. You're not supposed to interact with selectize directly.

To do what you describe you must bind the `selection` property to `ember-selectize`. Then, in your action you can just do `this.set('selection', null)`. You may get another `select-item' action  with a null param because it also fires on "deselections". Just conditionally ignore that inside the action. 

Remember: actions up, *data down*. So, if you want the component to reflect an empty state, just set the data that it is backing to be empty (null in this case).

**Comment by dfalling** [comment]
Ah, makes sense.  Thanks!
